# Generated by Django 4.0.1 on 2022-01-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0002_alter_pelicula_autores_alter_pelicula_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Imagen'),
        ),
    ]
